# Generated by Django 5.0.4 on 2024-12-09 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='garbagebag',
            name='tourist_spot_id',
        ),
        migrations.RemoveField(
            model_name='garbagebag',
            name='user_id',
        ),
        migrations.AddField(
            model_name='garbagebag',
            name='area_cm2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='garbagebag',
            name='height_cm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='garbagebag',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='garbagebag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='garbage_bags', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garbagebag',
            name='width_cm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='garbagebag',
            name='tourist_spot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='garbage_bags', to='garbage_analysis.touristspot'),
            preserve_default=False,
        ),
    ]
