# Generated by Django 5.0.4 on 2024-12-10 07:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_analysis', '0002_touristspot_remove_garbagebag_tourist_spot_id_and_more'),
        ('tourist_spots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagebag',
            name='tourist_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garbage_bags', to='tourist_spots.touristspot', verbose_name='観光地'),
        ),
        migrations.AlterModelOptions(
            name='garbagebag',
            options={'verbose_name': 'ゴミ袋', 'verbose_name_plural': 'ゴミ袋'},
        ),
        migrations.AlterField(
            model_name='garbagebag',
            name='area_cm2',
            field=models.FloatField(default=0.0, verbose_name='面積（cm²）'),
        ),
        migrations.AlterField(
            model_name='garbagebag',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='garbagebag',
            name='height_cm',
            field=models.FloatField(default=0.0, verbose_name='高さ（cm）'),
        ),
        migrations.AlterField(
            model_name='garbagebag',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='画像パス'),
        ),
        migrations.AlterField(
            model_name='garbagebag',
            name='points',
            field=models.FloatField(default=0.0, verbose_name='ポイント'),
        ),
        migrations.AlterField(
            model_name='garbagebag',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('verified', 'Verified')], default='issued', max_length=10, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='garbagebag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='garbagebag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garbage_bags', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='garbagebag',
            name='width_cm',
            field=models.FloatField(default=0.0, verbose_name='幅（cm）'),
        ),
        migrations.DeleteModel(
            name='TouristSpot',
        ),
    ]
