# Generated by Django 5.0.4 on 2024-12-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_analysis', '0003_alter_garbagebag_tourist_spot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagebag',
            name='created_at_timestamp',
            field=models.BigIntegerField(default=0, verbose_name='作成タイムスタンプ'),
        ),
    ]
