# Generated by Django 5.0.4 on 2024-12-07 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='観光地の名前')),
                ('entry_fee', models.PositiveIntegerField(verbose_name='入場料')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_tourist_spots', to=settings.AUTH_USER_MODEL, verbose_name='観光地運営者ユーザー')),
            ],
            options={
                'verbose_name': '観光地',
                'verbose_name_plural': '観光地',
            },
        ),
    ]
