# Generated by Django 5.0.4 on 2024-12-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reservation_date',
            field=models.DateField(blank=True, null=True, verbose_name='予約日'),
        ),
    ]
